### ISSUE TITLE
Bug: Dashboard

### ISSUE THREAD

**Issue by Jorerlol** [chrisbruford/knight-companion#7]
While logged in and open on any tab, selecting Dashboard on the bar will flash the login screen before showing the dashboard.

Reproduction steps:
1: Open app
2: Login
3: Select Dashboard

At this point, the login screen will open. It will remain on that screen for an undetermined amount of time (usually approx. half to one second) before displaying the dashboard.

**Comment by chrisbruford** [comment]
This is an issue with the way the app checks if you're logged in by routing you via the login page for an automatic check of status, which then routes you back to the dashboard if you are.

This can be fixed by using a guard to check auth status and then only redirecting to login page if necessary.
