### ISSUE TITLE
Feedback: Bounty Voucher Reporting

### ISSUE THREAD

**Issue by Jorerlol** [chrisbruford/knight-companion#9]
Currently, bounty vouchers (and most likely combat bonds) are reported in the following way:

Known faction - "Movement for LP 751-1 Independents: 30253"
Unknown faction - ": 53784"

The proposal is if the faction is unknown, to place "Unknown Faction" as the faction. Thus, the above would become:

Known faction - "Movement for LP 751-1 Independents: 30253"
Unknown faction - "Unknown Faction: 53784"

**Comment by chrisbruford** [comment]
This is an issue with the web app not the companion app - closing
